### ISSUE TITLE
.npmrc url cannot contain environment variables

### ISSUE THREAD

**Issue by jaredmcateer** [ryansonshine/semantic-release-codeartifact#33]
## Current Behavior

If you have a `.npmrc` url with an environment variable (in our case the account id) the release will fail when trying to verify the config

```
[2:02:22 PM] [semantic-release] › ✖  ENPMRCCONFIGMISMATCH Mismatch on CodeArtifact repository and npmrc registry
The registry set in the .npmrc of your project root does not match the CodeArtifact endpoint.

The .npmrc registry is 'https://my-private-${AWS_ACCOUNT_ID}.d.codeartifact.us-east-1.amazonaws.com/npm/my-private/.'
The CodeArtifact endpoint is 'https://my-private-***.d.codeartifact.us-east-1.amazonaws.com/npm/my-private/'.

AggregateError: 
    SemanticReleaseError: Mismatch on CodeArtifact repository and npmrc registry
        at Object.getError (/home/runner/work/design-system/design-system/node_modules/semantic-release-codeartifact/lib/src/get-error.js:11:12)
        at /home/runner/work/design-system/design-system/node_modules/semantic-release-codeartifact/lib/src/verify-npm.js:52:41
        at Generator.next (<anonymous>)
        at fulfilled (/home/runner/work/design-system/design-system/node_modules/semantic-release-codeartifact/lib/src/verify-npm.js:5:58)
    at /home/runner/work/design-system/design-system/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/work/design-system/design-system/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/design-system/design-system/node_modules/semantic-release/index.js:103:3)
    at async module.exports (/home/runner/work/design-system/design-system/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/home/runner/work/design-system/design-system/node_modules/semantic-release/cli.js:[55](https://github.com/morpheus-med/design-system/runs/6371374317?check_suite_focus=true#step:9:55):5)
```

## Expected Behavior

Should not fail here

## Steps to Reproduce the Problem

  1. Edit the `.npmrc` fixture to contain an environment variable in the unittests
        ```         
         jared@SleepyGary:~/projects/semantic-release-codeartifact$ git diff
         diff --git a/test/fixtures/files/.npmrc b/test/fixtures/files/.npmrc
         index a95360a..57d7c96 100644
         --- a/test/fixtures/files/.npmrc
         +++ b/test/fixtures/files/.npmrc
         @@ -1,2 +1,2 @@
         -registry=https://my-domain-000000000.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/
         -//my-domain-000000000.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/:always-auth=true
         +registry=https://my-domain-${AWS_ACCOUNT_ID}.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/
         +//my-domain-${AWS_ACCOUNT_ID}.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/:always-auth=true
        ```
  1. run `AWS_ACCOUNT_ID=000000000 npm test`

It's obviously because this is more or less a straight string equality check and I'm not sure what the proper fix should be.

## Environment

- Version: 0.0.0-development
- Platform: Linux
- Node.js Version: v16.14.2

**Comment by ryansonshine** [comment]
Thanks for opening the issue!

Is the environment variable also set in your build environment?

**Comment by ryansonshine** [comment]
@all-contributors add @jaredmcateer for bugs

**Comment by jaredmcateer** [comment]
Thanks for the quick response!
